/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XNlTLb7
 */
import { Link } from "react-router-dom";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Apple, Chrome } from "lucide-react";

export function LoginForm() {
  return (
    <div className="bg-gray-100 min-h-screen flex items-center justify-center">
      <div className="max-w-sm rounded-lg shadow-lg bg-white p-6 space-y-6 border border-gray-200 dark:border-gray-700">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            By logging in, you accept our{" "}
            <Link className="text-blue-500 hover:text-blue-700" to="#">
              terms{" "}
            </Link>
            and{" "}
            <Link className="text-blue-500 hover:text-blue-700" to="#">
              privacy policy
            </Link>
          </p>
        </div>
        <div className="space-y-10">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              placeholder="m@example.com"
              required
              type="email"
            />
          </div>
          <div className="flex items-center space-x-2">
            <hr className="flex-grow border-zinc-200 dark:border-zinc-700" />
            <span className="text-zinc-400 dark:text-zinc-300 text-sm">OR</span>
            <hr className="flex-grow border-zinc-200 dark:border-zinc-700" />
          </div>
          <div className="space-y-4">
            <Button
              className="w-full bg-[#4285F4] text-white"
              variant="outline"
            >
              <div className="flex items-center justify-center">
                <Chrome className="w-5 h-5 mr-2" />
                Login with Google
              </div>
            </Button>
            <Button className="w-full bg-black text-white" variant="outline">
              <div className="flex items-center justify-center">
                <Apple className="w-5 h-5 mr-2" />
                Login with Apple
              </div>
            </Button>
          </div>
          <div className="flex items-center justify-between">
            <Link
              className="text-blue-500 font-mono tracking-tighter  text-xs hover:text-blue-700"
              to="#"
            >
              Forgot password?
            </Link>
            <Link
              className="text-blue-500 font-mono tracking-tighter text-xs hover:text-blue-700"
              to="/sign-up"
            >
              Sign up
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
