/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XNlTLb7
 */
import AppleIcon from "@/assets/svg/apple.svg";
import GoogleIcon from "@/assets/svg/google.svg";
import FacebookIcon from "@/assets/svg/facebook.svg";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Link } from "react-router-dom";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
export function LoginForm() {
  return (
    <div className="bg-gray-100 animate__animated animate__fadeIn min-h-screen flex items-center justify-center">
      <div className="max-w-sm rounded-lg shadow-lg bg-white p-6 space-y-6 border border-gray-200 dark:border-gray-700">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            By logging in, you accept our{" "}
            <Link className="text-blue-500 hover:text-blue-700" to="#">
              terms{" "}
            </Link>
            and{" "}
            <Link className="text-blue-500 hover:text-blue-700" to="#">
              privacy policy
            </Link>
          </p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              placeholder="m@example.com"
              required
              type="email"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Password</Label>
            <Input
              id="password"
              placeholder="********"
              required
              type="password"
            />
          </div>
          <div className="flex items-center space-x-2">
            <hr className="flex-grow border-zinc-200 dark:border-zinc-700" />
            <span className="text-zinc-400 dark:text-zinc-300 text-sm">OR</span>
            <hr className="flex-grow border-zinc-200 dark:border-zinc-700" />
          </div>
          <div className="space-y-4">
            <Button className="w-full " variant="outline">
              <div className="flex items-center justify-center">
                <img src={GoogleIcon} className="w-5 h-5 mr-2" />
                Login with Google
              </div>
            </Button>
            <Button className="w-full bg-black text-white">
              <div className="flex items-center justify-center">
                <img src={AppleIcon} className="w-5 h-5 mr-2" />
                Login with Apple
              </div>
            </Button>
            <Button className="w-full" variant="outline">
              <div className="flex items-center justify-center">
                <img src={FacebookIcon} className="w-5 h-5 mr-2" />
                Login with Google
              </div>
            </Button>
          </div>
          <div className="flex items-center justify-between">
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button
                  variant="link"
                  className="text-blue-500 font-mono tracking-tighter  text-xs hover:text-blue-700"
                >
                  Forgot password?
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Verification Required</AlertDialogTitle>
                  <AlertDialogDescription>
                    Before proceeding, please check your email for a
                    verification link. And then you'll be able to login with the
                    new password that you set.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction className="px-0">
                    <Link to="/login">
                      <Button className="px-5">
                        Continue with Verification
                      </Button>
                    </Link>
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>

            <Link to="/sign-up">
              <Button
                className="text-blue-500 font-mono tracking-tighter text-xs hover:text-blue-700"
                variant="link"
              >
                Sign up
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
